blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Questions
    url: https://github.com/redhat-developer/vscode-extension-tester/discussions
    about: FAQ, Ideas, Q&A, ...
  - name: ğŸ“ Documentation
    url: https://github.com/redhat-developer/vscode-extension-tester/wiki
    about: Documentation with examples of usage.
