name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16 ]
        version:  [ min, 1.68.1, 1.69.2, 1.70.2, max ]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Dependencies
        run: |
          rm -f package-lock.json
          npm run prepare-deps
          npm install
          npm run build
          npm run prepare-test
      - name: Run Tests
        env: 
          CODE_VERSION: ${{ matrix.version }}
        run: |
          sudo apt-get install xvfb
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1920x1080x16 & 
          npm run ci-test
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-${{ matrix.version }}
          path: ~/test/**/screenshots/*.png
