name: ðŸ’Ž NodeJS CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [ lts/*, latest ]
    uses: ./.github/workflows/template-main.yaml
    with:
      version: max
      nodejs: ${{ matrix.node }}
