name: ğŸ“„ Runner CI - template

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      nodejs:
        required: false
        default: "20.x"
        type: string
      code_type:
        required: false
        default: "stable"
        type: string

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    env:
      CODE_TYPE: ${{ inputs.code_type }}
      CODE_VERSION: ${{ inputs.version }}
      TEST_RESOURCES: test-resources

    steps:
      - name: ğŸ‘·ğŸ» Checkout Repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.nodejs }}
          cache: npm

      - name: ğŸ”§ Install
        run: npm ci

      - name: ğŸ”§ Build
        run: npm run build

      - name: âœ¨ Code Formatter - Prettier
        run: npx prettier . --check

      - name: ğŸ”§ Install - ExTester Runner
        run: npm install --workspace=extester-runner

      - name: ğŸ”§ Install - Example Project
        run: |
          cd packages/extester-runner/src/ui-test/resources/example-project
          npm install
          npm run build

      - name: âš™ï¸ Allow unprivileged user namespace (ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: ğŸ” Run Unit Tests (macOS, windows)
        if: ${{ ! startsWith(matrix.os, 'ubuntu') }}
        run: npm run test:runner:unit

      - name: ğŸ” Run Unit Tests (linux)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run test:runner:unit

      - name: ğŸ” Run UI Tests (macOS)
        uses: nick-fields/retry@v3
        if: ${{ startsWith(matrix.os, 'mac') }}
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: npm run test:runner:ui
          on_retry_command: rm -rf "${RUNNER_TEMP}/extest-code"

      - name: ğŸ” Run UI Tests (windows)
        uses: nick-fields/retry@v3
        if: ${{ startsWith(matrix.os, 'win') }}
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: npm run test:runner:ui

      - name: ğŸ” Run UI Tests (linux)
        uses: nick-fields/retry@v3
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run test:runner:ui

      - name: ğŸ’¾ Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure() && inputs.nodejs != 'lts/*'
        with:
          name: runner-screenshots-${{ matrix.os }}-${{ inputs.version }}-node_${{ inputs.nodejs }}
          path: ${{ github.workspace }}/packages/extester-runner/**/screenshots/**/*.png

      - name: ğŸ’¾ Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure() && inputs.nodejs == 'lts/*'
        with:
          name: runner-screenshots-${{ matrix.os }}-${{ inputs.version }}-node_lts
          path: ${{ github.workspace }}/packages/extester-runner/**/screenshots/**/*.png
